import Link from 'next/link'
import '../styles.scss'
import './globals.css'
import '@fortawesome/fontawesome-svg-core/styles.css';
import { config } from '@fortawesome/fontawesome-svg-core';

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {  faLaptopCode } from '@fortawesome/free-solid-svg-icons';



config.autoAddCss = false; /* eslint-disable import/first */


export const metadata = {
  title: 'Product list',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
      <html lang="en">
          <body className="container mx-auto my-7 ">
              <div>
              <Link href="/" className='text-4xl'>
                      <FontAwesomeIcon className='text-2xl font-normal	' icon={faLaptopCode} /> Home
              </Link>
              </div>
              {children}
          
          </body>
    </html>
  )
}
