import Link from 'next/link'
import '../styles.scss'
import './globals.css'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {  faLaptopCode } from '@fortawesome/free-solid-svg-icons';

import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Product list',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
      <html lang="en">
          <body className="container mx-auto my-7 ">
              <div>
              <Link href="/" className='text-4xl'>
                  <FontAwesomeIcon  icon={faLaptopCode} /> Home
              </Link>
              </div>
              {children}
          
          </body>
    </html>
  )
}
